//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JackTheClipperCommon.Localization {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ClipperTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClipperTexts() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JackTheClipperCommon.Localization.ClipperTexts", typeof(ClipperTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ... wurde für sie angelegt.
        ///
        ///Sie können sich mittels folgender Angaben einloggen:
        ///Benutzername: {0}
        ///Passwort: {1}
        ///
        ///Bitte beachten Sie, dass das Passwort beim nächsten Login geändert werden muss.
        ///
        ///Mit freundlichen Grüßen,
        ///
        ///Jack the Clipper ähnelt.
        /// </summary>
        public static string AccountCreatedMailBody {
            get {
                return ResourceManager.GetString("AccountCreatedMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ihr Account bei &quot;Jack the Clipper&quot;... ähnelt.
        /// </summary>
        public static string AccountCreatedMailSubject {
            get {
                return ResourceManager.GetString("AccountCreatedMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es gibt Neuigkeiten bei &quot;Jack the Clipper&quot;... ähnelt.
        /// </summary>
        public static string DefaultMailSubject {
            get {
                return ResourceManager.GetString("DefaultMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ... wurde geändert.
        ///
        ///Sollten Sie nicht die Änderung Ihrer E-Mailadresse veranlasst haben, kontaktieren Sie bitte umgehend ihren Personalbeauftragten.
        ///
        ///Mit freundlichen Grüßen,
        ///
        ///Jack the Clipper ähnelt.
        /// </summary>
        public static string MailChangedMailBody {
            get {
                return ResourceManager.GetString("MailChangedMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ihre E-Mailadresse bei &quot;Jack the Clipper&quot;... ähnelt.
        /// </summary>
        public static string MailChangedMailSubject {
            get {
                return ResourceManager.GetString("MailChangedMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ... beitreten.
        ///
        ///Sie müssen die Registrierungsanfrage von {0} (E-Mail:{1}) genehmigen.
        ///Mit freundlichen Grüßen,
        ///
        ///Jack the Clipper ähnelt.
        /// </summary>
        public static string NewPendingUserMailBody {
            get {
                return ResourceManager.GetString("NewPendingUserMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein Benutzer möchte &quot;Jack the Clipper&quot;... ähnelt.
        /// </summary>
        public static string NewPendingUserMailSubject {
            get {
                return ResourceManager.GetString("NewPendingUserMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ... wurde geändert.
        ///
        ///Sollten Sie nicht die Änderung Ihres Passworts veranlasst haben, kontaktieren Sie bitte umgehend ihren Personalbeauftragten.
        ///
        ///Mit freundlichen Grüßen,
        ///
        ///Jack the Clipper ähnelt.
        /// </summary>
        public static string PasswordChangedMailBody {
            get {
                return ResourceManager.GetString("PasswordChangedMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ihr Passwort bei &quot;Jack the Clipper&quot;... ähnelt.
        /// </summary>
        public static string PasswordChangedMailSubject {
            get {
                return ResourceManager.GetString("PasswordChangedMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ... wurde zurückgesetzt. 
        ///
        ///Ihr neues Passwort lautet: {0}
        ///Dass Passwort muss beim nächsten Login geändert werden.
        ///
        ///Sollten Sie nicht die Änderung Ihres Passworts veranlasst haben, kontaktieren Sie bitte umgehend ihren Personalbeauftragten.
        ///
        ///Mit freundlichen Grüßen,
        ///
        ///Jack the Clipper ähnelt.
        /// </summary>
        public static string PasswordResetMailBody {
            get {
                return ResourceManager.GetString("PasswordResetMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ihr Passwort bei &quot;Jack the Clipper&quot;... ähnelt.
        /// </summary>
        public static string PasswordResetMailSubject {
            get {
                return ResourceManager.GetString("PasswordResetMailSubject", resourceCulture);
            }
        }
    }
}
